name: WorkFlow
on:
  push:
    branches:
      - feature-*
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log
        run: ls -R
